services:
  central-server:
    build:
      context: ./central-server
      dockerfile: DockerfileCentral
    ports:
      - "9090:9090"

  alice_white:
    build: ./empleados/Alice_White
    ports:
      - "8081:8081"

  bob_smith:
    build: ./empleados/Bob_Smith
    ports:
      - "8082:8082"

  carol_simpson:
    build: ./empleados/Carol_Simpson
    ports:
      - "8083:8083"

  david_black:
    build: ./empleados/David_Black
    ports:
      - "8084:8084"

  eva_brown:
    build: ./empleados/Eva_Brown
    ports:
      - "8085:8085"
