services:
  central-server:
    build:
      context: ./central-server
      dockerfile: DockerfileCentral
    ports:
      - "9090:9090"

  alice_white:
    build:
      context: ./empleados/Alice_White
      dockerfile: Dockerfile
    ports:
      - "8081:8081"


  bob_smith:
    build: 
      context: ./empleados/Bob_Smith
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  carol_simpson:
    build: 
      context: ./empleados/Carol_Simpson
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  david_black:
    build: 
      context: ./empleados/David_Black
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

  eva_brown:
    build: 
      context: ./empleados/Eva_Brown
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
