services:
  central-server:
    image: dfellig/deber-3:central
    ports:
      - "9090:9090"

  Alice_White:
    image: dfellig/deber-3:alice
    ports:
      - "8081:8081"

  Bob_Smith:
    image: dfellig/deber-3:bob
    ports:
      - "8082:8082"

  Carol_Simpson:
    image: dfellig/deber-3:carol
    ports:
      - "8083:8083"

  David_Black:
    image: dfellig/deber-3:david
    ports:
      - "8084:8084"

  Eva_Brown:
    image: dfellig/deber-3:eva
    ports:
      - "8085:8085"
